import House1 from '../public/houses/house1.png'
import Apartment1 from '../public/apartments/apartment1.png'
import Agent1 from '../public/agents/agent1.png'

export const housesData = [
    {
      id: 1,
      type: 'House',
      name: 'House 1',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'United States',
      date: '2020-01-12',
      address: 'Address 1',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '110000',
      agent: {
        image: Agent1,
        name: 'Agent 1',
        phone: '0123 456 78910',
      },
    },
    {
      id: 2,
      type: 'House',
      name: 'House 2',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 2',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '140000',
      agent: {
        image: Agent1,
        name: 'Agent 2',
        phone: '0123 456 78910',
      },
    },
    {
      id: 3,
      type: 'House',
      name: 'House 3',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'United States',
      date: '2020-01-12',
      address: 'Address 3',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '170000',
      agent: {
        image: Agent1,
        name: 'Agent 3',
        phone: '0123 456 78910',
      },
    },
    {
      id: 4,
      type: 'House',
      name: 'House 4',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 4',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '200000',
      agent: {
        image: Agent1,
        name: 'Agent 4',
        phone: '0123 456 78910',
      },
    },
    {
      id: 5,
      type: 'House',
      name: 'House 5',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'United States',
      date: '2020-01-12',
      address: 'Address 5',
      bedrooms: '5',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2015',
      price: '210000',
      agent: {
        image: Agent1,
        name: 'Agent 5',
        phone: '0123 456 78910',
      },
    },
    {
      id: 6,
      type: 'House',
      name: 'House 6',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 6',
      bedrooms: '6',
      bathrooms: '3',
      surface: '6200 sq ft',
      year: '2014',
      price: '220000',
      agent: {
        image: Agent1,
        name: 'Agent 6',
        phone: '0123 456 78910',
      },
    },
    {
      id: 7,
      type: 'Apartament',
      name: 'Apartament 1',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: Apartment1,
      country: 'India',
      date: '2020-03-12',
      address: 'Address 7',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1200 sq ft',
      year: '2012',
      price: '20000',
      agent: {
        image: Agent1,
        name: 'Agent 7',
        phone: '0123 456 78910',
      },
    },
    {
      id: 8,
      type: 'Apartament',
      name: 'Apartament 2',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: Apartment1,
      country: 'India',
      date: '2020-01-12',
      address: 'Address 8',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1000 sq ft',
      year: '2011',
      price: '30000',
      agent: {
        image: Agent1,
        name: 'Agent 8',
        phone: '0123 456 78910',
      },
    },
    {
      id: 9,
      type: 'Apartament',
      name: 'Apartament 3',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: Apartment1,
      country: 'Japan',
      date: '2020-01-12',
      address: 'Address 9',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1100 sq ft',
      year: '2011',
      price: '40000',
      agent: {
        image: Agent1,
        name: 'Agent 9',
        phone: '0123 456 78910',
      },
    },
    {
      id: 10,
      type: 'House',
      name: 'House 7',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 10',
      bedrooms: '5',
      bathrooms: '3',
      surface: '3200 sq ft',
      year: '2015',
      price: '117000',
      agent: {
        image: Agent1,
        name: 'Agent 10',
        phone: '0123 456 78910',
      },
    },
    {
      id: 11,
      type: 'House',
      name: 'House 8',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 11',
      bedrooms: '7',
      bathrooms: '2',
      surface: '2200 sq ft',
      year: '2019',
      price: '145000',
      agent: {
        image: Agent1,
        name: 'Agent 11',
        phone: '0123 456 78910',
      },
    },
    {
      id: 12,
      type: 'House',
      name: 'House 9',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'United States',
      date: '2020-01-12',
      address: 'Address 12',
      bedrooms: '4',
      bathrooms: '4',
      surface: '4600 sq ft',
      year: '2015',
      price: '139000',
      agent: {
        image: Agent1,
        name: 'Agent 12',
        phone: '0123 456 78910',
      },
    },
    {
      id: 13,
      type: 'House',
      name: 'House 10',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 13',
      bedrooms: '5',
      bathrooms: '2',
      surface: '5200 sq ft',
      year: '2014',
      price: '180000',
      agent: {
        image: Agent1,
        name: 'Agent 13',
        phone: '0123 456 78910',
      },
    },
    {
      id: 14,
      type: 'House',
      name: 'House 11',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'United States',
      date: '2020-01-12',
      address: 'Address 14',
      bedrooms: '5',
      bathrooms: '2',
      surface: '3200 sq ft',
      year: '2011',
      price: '213000',
      agent: {
        image: Agent1,
        name: 'Agent 14',
        phone: '0123 456 78910',
      },
    },
    {
      id: 15,
      type: 'House',
      name: 'House 12',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: House1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 15',
      bedrooms: '4',
      bathrooms: '3',
      surface: '5200 sq ft',
      year: '2013',
      price: '221000',
      agent: {
        image: Agent1,
        name: 'Agent 15',
        phone: '0123 456 78910',
      },
    },
    {
      id: 16,
      type: 'Apartament',
      name: 'Apartament 16',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: Apartment1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 16',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1300 sq ft',
      year: '2011',
      price: '21000',
      agent: {
        image: Agent1,
        name: 'Agent 16',
        phone: '0123 456 78910',
      },
    },
    {
      id: 17,
      type: 'Apartament',
      name: 'Apartament 17',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: Apartment1,
      country: 'United States',
      date: '2020-01-12',
      address: 'Address 17',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1000 sq ft',
      year: '2012',
      price: '32000',
      agent: {
        image: Agent1,
        name: 'Agent 17',
        phone: '0123 456 78910',
      },
    },
    {
      id: 18,
      type: 'Apartament',
      name: 'Apartament 18',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: Apartment1,
      country: 'Canada',
      date: '2020-03-12',
      address: 'Address 18',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1200 sq ft',
      year: '2010',
      price: '38000',
      agent: {
        image: Agent1,
        name: 'Agent 18',
        phone: '0123 456 78910',
      },
    },
  ];